### ISSUE TITLE
Compatibility with tectonic

### ISSUE THREAD

**Issue by rillian** [schlcht/microtype#18]
## Description
I've been trying to use the [tectonic](https://github.com/tectonic-typesetting/tectonic/) front-end. Today I ran into an issue with the microtype spacing support.
```
$ tectonic microtype.tex 
Running TeX ...
error: microtype.tex:3: Package microtype Error: The spacing feature only works with pdftex 1.40
(microtype)                or newer. Switching it off.

See the microtype package documentation for explanation.
Type  H <return>  for immediate help
error: halted on potentially-recoverable error as specified
```

Any idea what's missing from the tectonic engine for this to work? Tectonic is based on XeTeX, so I was surprised it wasn't supported.

_Please also indicate the engine(s) with which the issue occurs: pdfTeX/LuaTeX/XeTeX_

tectonic (based on XeTeX)

_Links to <tex.stackexchange.com> discussion if appropriate_

## Minimal example demonstrating the issue
```
\documentclass{article}
\usepackage[spacing]{microtype}
\begin{document}
Hello, bug!
\end{document}
```

**Comment by schlcht** [comment]
Of the microtypographic features, only protrusion is supported by xetex (see the table on p. 6 in microtype.pdf). So as tectonic is based on xetex, it is expected behaviour that the spacing feature doesn't work. I don't know whether tectonic can be persuaded to use pdftex instead, but that would be the only way to get the extra spacing.

**Comment by rillian** [comment]
Ah, I see. Thanks for clarifying. I'll stick with pdftex for this document.
