### ISSUE TITLE
Inconsistent line breaks after full-width box

### ISSUE THREAD

**Issue by joel-coffman** [schlcht/microtype#7]
## Description

The microtype package interferes with line breaks following a full-width box in certain instances. More specifically, text that follows a box that is the width of the current line does *not* appear on the next line (as expected) but extends into the margin. Weirdly, the starting letter of the box appears to be significant, as certain starting letters exhibit this behavior whereas others don't (see minimal working example below).

To be clear, I'm not completely certain that this issue is actually a bug, but the behavior differs significantly from LaTeX's when the microtype package is not used.

_Please also indicate the engine(s) with which the issue occurs: **pdfTeX**/LuaTeX/XeTeX_

``` text
pdfTeX 3.141592653-2.6-1.40.22 (TeX Live 2021/MacPorts 2021.58693_1)
kpathsea version 6.3.3
Copyright 2021 Han The Thanh (pdfTeX) et al.
There is NO warranty.  Redistribution of this software is
covered by the terms of both the pdfTeX copyright and
the Lesser GNU General Public License.
For more information about these matters, see the file
named COPYING and the pdfTeX source.
Primary author of pdfTeX: Han The Thanh (pdfTeX) et al.
Compiled with libpng 1.6.37; using libpng 1.6.37
Compiled with zlib 1.2.11; using zlib 1.2.11
Compiled with xpdf version 4.03
```

The microtype version is `2021/03/14 v2.8c`.

The behavior is consistent across multiple versions of pdflatex and the microtype package (TeX Live 2016, 2019, and 2020).

## Minimal example demonstrating the issue

``` latex
\documentclass{article}
\usepackage[verbose]{microtype}

\begin{document}

\noindent
\makebox[\linewidth][l]{An example}
\makebox[\linewidth][l]{More text that should appear on next line}

\bigskip
\bigskip

\noindent 
Weirdly, the starting letter appears to be significant:
\medskip

\noindent 
\makebox[\linewidth][l]{This one has the same issue as the first}
\makebox[\linewidth][l]{More text that should appear on next line}

\bigskip

\noindent
\makebox[\linewidth][l]{But not this one for some reason}
\makebox[\linewidth][l]{More text that should appear on next line}

\end{document}
```

**Comment by joel-coffman** [comment]
The issue appears to be caused by protrusion in the left margin. Adding `\noprotrusion` prior to the text in the box (e.g., `\makebox[\linewidth][l]{\noprotrusion An example}`) prevents the second box from extending into the right margin.

While it makes sense that protrusion in the left margin leaves space after the first "full-width" box, I don't understand why the later text isn't wrapped to the next line. It seems like the subsequent box, which is much wider than the remaining space on the first line, should automatically wrap to the next line (as occurs when the microtype package isn't used).

Stack Exchange answers that helped to identify the cause of this issue and alternative workarounds:

* Wrong alignment with microtype: "(3D)" is too far left; inside enumerate. Is it by design?: https://tex.stackexchange.com/a/596023
* Disable protrusion from microtype for just one word: https://tex.stackexchange.com/a/285241

Both solutions (i.e., inserting `\makebox[0pt]{}` or `\kern1sp`) also work.

**Comment by schlcht** [comment]
You're right that this is a side effect of protrusion. To explain: LaTeX's `\makebox` sets the text in an `\hbox` first (at which point there will be no protrusion), then unboxes this box (which has been set to be `\linewidth` wide) into the main vertical list; here the margin kern will be inserted, so that the actual text is shorter than `\linewidth`. The resulting line break is the same as you would get with, e.g., `\makebox[0.99\linewidth]{...}`.

To fix this systematically, the LaTeX command `\@begin@tempboxa` would have to be patched: 

```
\makeatletter
\def\noprotrusionifhmode{\ifhmode\kern-\p@\kern\p@\fi}
\long\def\@begin@tempboxa#1#2{%
   \begingroup
     \setbox\@tempboxa#1{\color@begingroup\leftprotrusion#2\noprotrusionifhmode\color@endgroup}%
     \def\width{\wd\@tempboxa}%
     \def\height{\ht\@tempboxa}%
     \def\depth{\dp\@tempboxa}%
     \let\totalheight\@ovri
     \totalheight\height
     \advance\totalheight\depth}
\makeatother
```

Or, with a current `microtype`: 

```
\makeatletter
\def\noprotrusionifhmode{\ifhmode\kern-\p@\kern\p@\fi}
\begingroup
\@makeother\#
\expandafter\endgroup\@firstofone{%
\MT@define@patch{makebox}
  {\MT@patch@patch\@begin@tempboxa{#2}{\leftprotrusion#2\noprotrusionifhmode}}{}}
\makeatother
```

Remark 1: I'm using `\noprotrusionifhmode` instead of the usual  `\noprotrusion` because the latter would add extra vertical space for `\parbox`.

Remark 2: Unfortunately, adding `\rightprotrusion` at the right hand side doesn't work. You may still insert this command manually for right-aligned boxes: `\makebox[\linewidth][r]{example\rightprotrusion{--}]`

**Comment by joel-coffman** [comment]
Thanks for the explanation!

Out of curiosity, why does the second box extend into the (right) margin? I understand why there's space remaining to start the box on the same line as the first, but given the size of the box (e.g., `0.99\linewidth`), I would expect it to be moved to the next line, similar to adding an explicit line break after the first box.

**Comment by schlcht** [comment]
I agree it seems unexpected, but that's just how tex breaks lines. The boxes created by `\makebox` are added in horizontal mode, so the same rules apply as for a normal paragraph. 

```
\documentclass[draft]{article}
\parindent0pt
\begin{document}
\leavevmode % added by \makebox
\hbox to .999\linewidth{abc}
\hbox{def}

\medskip
\setbox0\hbox{Word\kern.1pt}
\hsize=\wd0
\hrule width\wd0 % shows current line width
\medskip
Word Word
\end{document}
```

In your case, I would probably just add `\par` or `\\` after the boxes.

Also, just for the record, I will probably not add this to the default patches. I have a hunch that the use cases for `\makebox` are just too diverse, so that there's no one-size-fits-all. Thanks for your report anyway!
