### ISSUE TITLE
item patches clash with paragraph tagging

### ISSUE THREAD

**Issue by u-fischer** [schlcht/microtype#8]
## Description
As has been reported in the tagpdf issue tracker https://github.com/u-fischer/tagpdf/issues/49 the patches microtype adds to `\item` clash with the automatic paragraph tagging of tagpdf. 

The problem is that the paragraph hooks are executed twice at the item as microtype stores something in a box and issues a `\noindent` in the box which triggers the hooks. Imho the right fix is to use `\RawNoindent`  instead. The difference can be shown also without tagpdf:

~~~~
\documentclass{article}
\usepackage{microtype}
\makeatletter
%\patchcmd{\MT@get@prot}{\noindent}{\RawNoindent}{}{\fail}
\AddToHook{para/begin}{\show\blub}
\makeatletter
\begin{document}
\begin{quotation}
Hello world
\end{quotation}

\end{document}
~~~~

Without the patch `\show\blub` is shown twice, with the patch only once.

**Comment by schlcht** [comment]
Thanks, I can change that. 

However, it seems to me that the problem is a bit more general with `tagpdf` (or the new hook management?), because it will fail in the same way with other packages that do some "test typesetting". Just off the top of my head, think of `tabularx` and `csquotes`'s `\blockquote`.

**Comment by u-fischer** [comment]
Yes test typesetting is also a problem and I'm already pondering about it too. One probably will have to unify the amsmath if@measuring and other "trial" booleans. Then tagging could simply pause in such contexts.
